### ISSUE TITLE
I need collaborator.

### ISSUE THREAD

**Issue by GhostService** [NebulaServices/3kh0#17]
### What is this request?

Something else

### If you said other in the dropdown above, please specify what below

Collaborator needed

### Please describe the new feature here

Hello! I Am Ghost (discord @ghostyt7582) and I am a collaborator on the original 3kh0 project. Can I have collaborator so i can keep fixing issues? (if you dont think im a collab just ask Echo.)

**Comment by clovercrash** [comment]
No, sorry. You haven't made any significant contributions that improved the code, added to it in a meaningful way
